### ISSUE TITLE
[Arena] Shadow Sight is a buff instead of being a debuff.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#115]
**Description:**
Shadow Sight, the effect of walking into one of the purple cubes during any arena match, should be a debuff and not a buff. With it being a buff players could cancel it and not suffer the aditional 5% damage taken during it's duration.

**Expected behaviour:**

It should be a debuff.

**Steps to reproduce the problem:**

1. Debug arena and wait for the "eyes" to spawn 
2. Walk into one of them
3. They appear as a buff

**rev. hash/commit:** 

latest

**Comment by kelno** [comment]
Apparently fixed, test again?
