### ISSUE TITLE
[Mage] Empowered Fireball makes Fireball's DoT scale with spell damage.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#159]
**Description:**

Fireball DoT is scaling with spell damage, it gains it from http://tbc.cavernoftime.com/spell=31660

**Current behaviour:**

Fireball's DoT scales with the talent, making it scale with mage's spell damage.

**Expected behaviour:**
The DoT effect should not scale with the talent and gain from bonus spelldamage. It should only scale with modifiers - percentage talents and debuffs.

**Steps to reproduce the problem:**

1. Cast Fireball on a target without any bonus spell damage gear and examine the Fireball DoT values.
2. Equip some spell damage gear and repeat step 1
3. Skill Empowered Fireball
4. Repeat steps 1 and 2

**rev. hash/commit:** 

Sunstrider rev. 10154 (1ebf0609a394) 2019-01-11 00:00:40 +0100 (master branch) (Unix, DEBUG, Static)

**Sources**:
The values Fireball's DoT does are very low compared to values on PTR - Empowered Fireball did not make it scale with spell damage.
https://youtu.be/fQqx9YGr8xo?t=36
https://youtu.be/gSPpi7NfdEU?t=62

**Comment by kelno** [comment]
Don't forget that the fire dot also gets the remainder of the previous fire dot if it overrides one, it could throw away your calculations here.
Can you provide the numbers here as you did on the druid bloom issue?

**Comment by Jerrythemagicdog** [comment]
It's about fireball's DoT that it has by itself, not the Ignite talent that works the way you described.

Tooltip for Rank 1 Fireball: 

> Hurls a fiery ball that causes 15 - 22 Fire damage and an additional 1 Fire damage over 4 sec.

**Comment by kelno** [comment]
So it should always tick at 31-33 whatever spell power you have?

**Comment by Jerrythemagicdog** [comment]
That depends on the talents you've chosen - flat fire damage modifier talents should affect this and debuffs increasing fire damage - just the DoT should not take your spell damage into consideration.

**Comment by kelno** [comment]
Fixed in 10520
