### ISSUE TITLE
[Warrior] Spell Reflection doesn't cancel when shield is unequipped

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#183]
**Description:**
Copy pasting from: https://github.com/Nqsty/Sunstrider-Classes-Issues/issues/87

> ID: 23920
> 
> Spell reflection aura should only be active while the warrior got a shield equiped, once the shield is unequipped, the spell reflection should also fade. [BUG] Spell reflection aura doesn't fade even if you equip a 2H weapons.
> 
> Sources: tooltip (Raise your shield, reflecting the next spell cast on you. Lasts 5 sec. Requires: Shields, Battle Stance, Defensive Stance)

**Current behaviour:**

Spell Reflection doesn't cancel after unequipping shields.

**Steps to reproduce the problem:**

1. Equip a shield on a warrior and cast Spell Reflection
2. Unequip the shield / equip a 2hander
3. Spell Reflection buff persists

**rev. hash/commit:** 
Sunstrider rev. 10283 (2e80439) 2019-01-22 18:43:47 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Should be fixed by 12deac15c9a482396fa5be85fef4ac2e6118aba6 
But need test
