### ISSUE TITLE
NPCs not replacing properly after infernal rain in Honor Hold

### ISSUE THREAD

**Issue by SUN-Leekie** [ValorenWoW/sunstrider-issues#19]
**Description:**

There is an hourly event triggered by Watch Commander Leonus shouting to take cover from the infernal rain causing chaos in Honor Hold where NPCs are running around. When the event is over, all NPCs should replace themselves properly.

**Current behaviour:**

NPCs doesnt replace themselves properly causing weird placements in Honor Hold.
Watch Commander Leonus and his closest Honor Hold Archer are affected by the "fear" effect.
"Fear Controller" NPC (id: 19393) are affected by the "fear" effect, that seems pretty weird.

**Expected behaviour:**

Only on the ground NPCs should be affected by the "fear" effect.
Watch Commander Leonus and his closest Honor Hold Archer should not be affected by the "fear" effect as they are looking from above.

**Steps to reproduce the problem:**

Trigger the event.
Check `npc_watch_commander_leonus`.

**Comment by kelno** [comment]
fear controller being affected is another bug, I'll also check it

**Comment by SUN-Leekie** [comment]
@kelno The fear also affects NPCs in the inn and War Horses. It shouldnt.

**Comment by talamortis** [comment]
i will look into this issue now see if i can come up with anything
