### ISSUE TITLE
[Karazhan] Curator Sparks path inside textures and fall under the ground.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#232]
**Description:**
When positioned in a very specific way, The Curator's Astral Flares (17096) path inside the pillar and fall under the map not doing damage to the players. It can be abused to not take damage from the sparks allowing to ignore them.

![wowscrnshot_021219_111332](https://user-images.githubusercontent.com/46463908/52636836-97b27200-2ec5-11e9-872b-92eb2f576715.jpg)

In this screenshot the Astral Flares are trapped inside the pillar, not doing damage to players.

**Comment by kelno** [comment]
mmaps were missing
