### ISSUE TITLE
[#130] [Paladin] Judgement of Wisdom restores Creature mana instead of Player mana

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#334]
<a href="https://github.com/plutonium447"><img src="https://avatars0.githubusercontent.com/u/40911527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [plutonium447](https://github.com/plutonium447)**
_Friday Jan 04, 2019 at 05:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/130_

----

**Current behavior:**
Judgement of Wisdom will grant mana to the creature is it applied on when struck by players. This occurs with all ranks of the spell.

--Player attacks mob with JoW.
--Mob receives mana.

![wowscrnshot_010419_152918](https://user-images.githubusercontent.com/40911527/50674885-d25afc00-1035-11e9-910d-2c8f4c012fe2.jpg)
![wowscrnshot_010419_152927](https://user-images.githubusercontent.com/40911527/50674887-dc7cfa80-1035-11e9-8341-40cb7964af32.jpg)

**Expected behavior:**
Judgement of Wisdom will only grant mana to the player that triggered the attack.

--Player attacks mob with JoW.
--Player recieves mana.

**Steps to recreate issue**
Step 1: Cast Seal of Wisdom, then Judgement on a mob
Step 2: Hit it with a melee weapon or damaging spell
Step 3: notice when the mob starts regaining mana.

**id's:**
[debuff] Judgement of Wisdom (20353) _rank 3_
[spell] Seal of Wisdom (20357) _rank 3_

**Source(s)**
https://classicdb.ch/?spell=20353
https://classicdb.ch/?spell=20357
_had to use classicdb because other DBs had deleted the spell entries_

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 07, 2019 at 08:38 GMT_

----

Fixed with 10114

**Comment by ccwower** [comment]
Hello, brother administrator, I am a programming student from the Chinese community. As far as I know, Sunstrider also has members participating in China. I hope I can join and get core code support from you! I will continue to give feedback on bugs submitted by players and players in China

Can you invite me to join the closed source group?

**Comment by ccwower** [comment]
Hello, brother administrator, I am a programming student from the Chinese community. As far as I know, Sunstrider also has members participating in China. I hope I can join and get core code support from you! I will continue to give feedback on bugs submitted by players and players in China

Can you invite me to join the closed source group? Hope to share closed source warehouse
