### ISSUE TITLE
[#222] Quest Mob: The Kurken is Lurkin'

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#370]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silumor](https://github.com/silumor)**
_Tuesday Jan 29, 2019 at 03:17 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/222_

----

**Comment by aiacos16** [comment]
KURKEN got a bug can't be tamed by hunters
