### ISSUE TITLE
[#57] Bleeding Hollow archer targeting player while out of combat

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#426]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 10:59 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/57_

----

Current behavior:
NPC targets player after a wipe while out of combat

Expected behavior:
The mob should be neutral

Step 1: Engage mob and wipe
Step 2: Run back in after death

![wowscrnshot_121718_195423](https://user-images.githubusercontent.com/45530324/50083168-9dca0080-023e-11e9-9ce9-dc3f195c08d2.jpg)
![wowscrnshot_121718_195432](https://user-images.githubusercontent.com/45530324/50083169-9e629700-023e-11e9-8217-b304fd635b6d.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Dec 17, 2018 at 17:09 GMT_

----

https://github.com/Nolin7777/TBC-Bugtracker/issues/17 strikes back

**Comment by kelno** [comment]
<a href="https://github.com/Nqsty"><img src="https://avatars3.githubusercontent.com/u/11685475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nqsty](https://github.com/Nqsty)**
_Tuesday Jan 01, 2019 at 23:10 GMT_

----

Still an issue with guid 202648.

**Comment by emorelix** [comment]
![wowscrnshot_022319_195248](https://user-images.githubusercontent.com/47015256/53284299-6d569380-37a6-11e9-97a4-3798e08e13bd.jpg)

Yep

**Comment by kelno** [comment]
Duplicate https://github.com/ValorenWoW/sunstrider-issues/issues/250
