### ISSUE TITLE
[#72] [Mage] Clearcasting is proccing on damage ticks of channeled spells

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#433]
<a href="https://github.com/kekrat"><img src="https://avatars0.githubusercontent.com/u/45924491?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kekrat](https://github.com/kekrat)**
_Wednesday Dec 19, 2018 at 02:29 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/72_

----

![image](https://user-images.githubusercontent.com/45924491/50194590-b5fd6500-038f-11e9-8b3f-43c0b8d3b0ab.png)

Current behaviour: 

When casting a channeled spell such as "Blizzard" or "Arcane Missiles" the mage will proc the talent "Arcane Concentration" gaining "Clearcasting" from damage ticks subsequent to the initial cast of that spell. The mage may be able to proc the talent several times in 1 channel from numerous damage ticks. Through approximately 20 minutes of testing I was unable to proc the talent "Arcane Concentration" gaining "Clearcasting" from the **initial cast** of any channeled spell such as "Blizzard" or "Arcane Missiles" 

Expected behaviour:

When casting a channeled spell such as "Blizzard" or "Arcane Missiles" the mage should only be able to proc the talent "Arcane Concentration" and gain "Clearcasting" from the **initial cast** of the spell (i.e when mana is consumed). Damage ticks from the duration of the channel should not trigger the talent "Arcane Concentration" and allow the mage to gain "Clearcasting".

Steps to reproduce the problem:

1. Ensure Mage conducting the test has the talent "Arcane Concentration"
2. Find enemy mob or mobs.
3. Attack mobs with channeled spells such as "Blizzard" or "Arcane Missiles"
4. Observe the nature in which "Arcane Concentration" triggers and the mage gains "Clearcasting"

IDs
[Spell] Blizzard (27085 or 42198) 
[Spell] Arcane Missiles (10274 or 10212)
[Spell] Arcane Concentration (12577)
[Spell] Clearcasting (12536)

Evidence to support the nature in which Arcane Missiles should behave:

Changed in 3.3.0:

"Arcane Concentration: The interaction of this talent with Arcane Missiles has been restructured. Instead of an Arcane Missiles cast triggering the talent, each missile has an independent (but reduced) chance to trigger this talent. In addition, the talent will no longer sometimes be triggered from misses by Arcane Missiles, Arcane Blast, and Blizzard."

Unable to find evidence for Blizzard after brief search, my expectation and knowledge of TBC mechanics is that they should both behave the same.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Thursday Dec 20, 2018 at 22:33 GMT_

----

Interesting, it seems we have TLK behavior implemented.

**Comment by kelno** [comment]
<a href="https://github.com/Nqsty"><img src="https://avatars3.githubusercontent.com/u/11685475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nqsty](https://github.com/Nqsty)**
_Thursday Jan 03, 2019 at 17:58 GMT_

----

From Vanilla but mechanics didnt change in TBC:
Blizzard
First proc: https://youtu.be/16l2kJPM0D0?t=87

Arcane Missiles:
https://youtu.be/K4RjdUHbA8Y?t=151

**Comment by Jerrythemagicdog** [comment]
https://wowwiki.fandom.com/wiki/Arcane_Concentration
https://wow.gamepedia.com/Arcane_Concentration

> Further, Blizzards often proc clearcasting when allowed to run to their full duration, due to the large number of times Blizzard strikes and thus has a chance at proc'ing, which can sometimes mean that you can chain two, three, or even four Blizzards for no mana cost that all (combined with Arcane Potency) have a +30% crit chance. It's a fatal barrage. 

> Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself.

So, Blizzard can trigger it on each tick but Arcane Missiles only on the first one.

**Comment by Jerrythemagicdog** [comment]
**Some sources**:
https://wowwiki.fandom.com/wiki/Arcane_Concentration?oldid=1432055
Allakhazam: 

> Clearcasting will only proc off of the first casting of a spell. As soon as you elect to cast the chance is rolled and then you will enter Clearcast prior to the completion of the spell. If I Clearcast off of the casting of an Arcane Missles then the 15 second countdown on Clearcast begins at the same moment of the 5 second channel for Arcane Missle.
> 
> Actually, that's not 100% correct. The Clearcasting is rolled at the moment that the mana is used. For casting bar spells like Frostbolt it will proc at the end of the casting. For channel spells you use the mana at the begining of the spell and that's when the Clearcasting is rolled.

**Comment by kelno** [comment]
Fixed 10594

**Comment by kelno** [comment]
To detail this:
We currently made it so it procs on first tick rather than "on cast" like in the video. (doing it on cast would have been a lot more complicated to do, for no real benefit)
Also the proc chance can happen only once regardless of the number of targets.

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/91fb8f577bbdc9455f9fd91451cdad4c7b9abdda
