### ISSUE TITLE
[#89] Mining nodes only have 1 charge of ore in them

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#437]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 24, 2018 at 00:24 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/89_

----

Current behaviour:
When I mine 181556 (Adamantite deposit) it only has 1 charge before disappearing

https://tbc-twinhead.twinstar.cz/?object=181556

Expected behaviour:
Deposits should have 2-4 charges before disappearing

Steps to reproduce the problem:

Mine an adamantite deposit

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 24, 2018 at 02:21 GMT_

----

Tested a rich deposit and had the same issue (only 1 charge)

**Comment by kakarotkaruma** [comment]
I also had this issue

**Comment by kelno** [comment]
Fixed with 10658
