### ISSUE TITLE
[#141] [Hunter] Flare

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#449]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Tuesday Jan 08, 2019 at 10:32 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/141_

----

http://wowwiki.wikia.com/wiki/Flare

Using Flare, the animation begins and mobs/players do not get revealed until the animation is complete and the flare reaches the ground.

Using Flare should reveal the selected area instantly, while also causing the animation to begin.
IT should reveal in that area regardless of the animation.

Will find some PvP videos as evidence.

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Wednesday Jan 09, 2019 at 04:19 GMT_

----

Same with the third video; the rogue was moving from the right to left and hit the AoE while the flare was mid-air and was revealed as soon as he entered it

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Wednesday Jan 09, 2019 at 05:47 GMT_

----

2nd video - rogue is revealed as he runs over it with sprint, wasnt hit by it directly.
Hunter also has 220ms so can be a bit slow video animation reveal.

3rd video - agree with Kaz

4th video - same as 3rd, Rogue runs into the radius of flare after it is cast.
Animation is not complete.

Last video - instant.

Per patch notes, no changes were made to Flare other than the Cooldown during TBC.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Saturday Jan 12, 2019 at 09:47 GMT_

----

So the conclusion here is that it should be instant and currently isn't, izdatright?

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Saturday Jan 12, 2019 at 09:49 GMT_

----

Yes sir @kelno

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Saturday Jan 12, 2019 at 09:52 GMT_

----

Thank you

**Comment by woiwoz** [comment]
fixd

**Comment by kelno** [comment]
Fixed with 10532

**Comment by artieau** [comment]
Confirmed working, thanks :)
