### ISSUE TITLE
[#169] Disease cleanse totem

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#467]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silumor](https://github.com/silumor)**
_Saturday Jan 26, 2019 at 12:10 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/169_

----

Had a disease called "Bonechewer Rot" Spell ID 33951

Dropped disease cleanse totem (spellid 8170) does not remove disease from self or party 

It should clear the disease

**Comment by woiwoz** [comment]
Finish fix

**Comment by kelno** [comment]
Fixed in 10524
