### ISSUE TITLE
[#173] [Quest] Disrupt Their Reinforcements # 10208

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#469]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Saturday Jan 26, 2019 at 13:13 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/173_

----

The use of quest item To'arch 's Primers should be used on the two green portals once the player has acquired 4 x Demonic Rune Stone. Currently the portals are not able to be clicked on, or item used manually on the portal.

The portal should consume the 4 x Demonic Rune Stone and interact with the player.

**Comment by kelno** [comment]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tamosheik](https://github.com/Tamosheik)**
_Saturday Jan 26, 2019 at 20:44 GMT_

----

To'arch's Primers - Item ID# 28478

**Comment by Jerrythemagicdog** [comment]
Could've been the gameobject issue that's now fixed. Need retest

**Comment by artieau** [comment]
Fixed a while back, thanks.
