### ISSUE TITLE
[#175] Stealth drop on combat initiation

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#471]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Saturday Jan 26, 2019 at 14:22 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/175_

----

Patch:
PTR

Current behaviour:
Stealth fades instantly on monster aggro, secondarily monsters are alerted to your presence in stealth from tremendous distances

Expected behaviour:
Should remain in stealth until an ability or attack lands which causes stealth to fade

Steps to reproduce the problem:

Be in stealth,
Move toward monster,
Have monster see you and become aggressive
![stealth fade instantly on aggro](https://user-images.githubusercontent.com/46757539/51788421-0909d980-21d2-11e9-83dd-422c4ef5eeed.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 28, 2019 at 13:38 GMT_

----

Need a video source on that one

**Comment by Desparto** [comment]
I've been looking for a video but can't find one, but the initial report is correct. Combat itself shouldn't break stealth. e.g. in pvp, priests would mass dispel to try and hit a rogue in stealth to get in combat and prevent themselves being sapped, but this wouldn't bring the rogue out of stealth.

**Comment by woiwoz** [comment]
Based on years of experience in the game, it is very sure that this is indeed a BUG. You should not break the stealth until the target does no harm to the player.

**Comment by Desparto** [comment]
Patch notes for Mass Dispel: 
Patch 2.2.0 (25-Sep-2007): Has a chance to be resisted when dispelling immunity effects. This will be displayed in the combat log. In addition, it will no longer cause rogues and druids in Cat Form to lose Stealth. The flashing area graphic has been removed. 
Patch 2.0.3 (09-Jan-2007): "Mass Dispel" will no longer cause stealthed Rogues and prowling Druids to lose stealth. 

Note - Mass Dispel would still place both priest and druid/rogue in combat. This thread (from WotLK but still accurate) has multiple comments explaining Mass Dispel will place in combat http://www.arenajunkies.com/topic/146877-how-to-dodge-the-sap/

**Comment by kelno** [comment]
Fixed with 10719
