### ISSUE TITLE
[#179] Recently bandaged debuff does not prevent using bandages

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#473]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Saturday Jan 26, 2019 at 15:12 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/179_

----

Patch:
PTR

Current behaviour:
Able to spam bandages one after another

Expected behaviour:
Recently bandaged debuff should prevent use of bandages until it has expired.

Steps to reproduce the problem:

Step 1: Use netherweave bandage.
Step 2: Immediately use netherweave bandage

**Comment by kelno** [comment]
<a href="https://github.com/Tamosheik"><img src="https://avatars2.githubusercontent.com/u/40758487?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tamosheik](https://github.com/Tamosheik)**
_Saturday Jan 26, 2019 at 20:42 GMT_

----

Recently Bandaged - Spell ID# 11196

**Comment by soup1234** [comment]
Still doing this, just duelled someone and they could continually first-aid
