### ISSUE TITLE
[#209] [MAGE][SPELL] Summon Water Elemental not working

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#493]
<a href="https://github.com/dreapon"><img src="https://avatars1.githubusercontent.com/u/46831677?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dreapon](https://github.com/dreapon)**
_Monday Jan 28, 2019 at 03:19 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/209_

----

**Patch:**
2.4.3

**Server Version:**
10296

**Current behaviour:**
When casting the Summon Water Elemental spell, the spell goes on cooldown but nothing else happens

**Expected behaviour:**
A pet water elemental should be spawned under the control of the mage

**Steps to reproduce the problem:**

1. Spec Frost and put point in Summon Water Elemental talent at bottom of Frost tree
2. Cast Summon Water Elemental spell

![test3](https://user-images.githubusercontent.com/46831677/51812838-f93be380-22fe-11e9-9198-95ea6aba7587.gif)

**Note:**
Tested both in and out of combat

**IDs**
[Spell] Summon Water Elemental (31687)

**Source**
http://db.hellfire-tbc.com

**Comment by kelno** [comment]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Cheelout](https://github.com/Cheelout)**
_Monday Jan 28, 2019 at 05:06 GMT_

----

Can confirm this was working ~2 weeks ago but is borked now :(

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 28, 2019 at 13:53 GMT_

----

I could not reproduce this one, can you specify server revision here?

**Comment by kelno** [comment]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Cheelout](https://github.com/Cheelout)**
_Tuesday Jan 29, 2019 at 07:49 GMT_

----

![image](https://user-images.githubusercontent.com/38281939/51892636-aa717500-23f6-11e9-8f93-1b857722c594.png)

**Comment by qoth** [comment]
Can confirm working. 

![image](https://user-images.githubusercontent.com/35262513/52937794-00ab5580-33b0-11e9-84d6-89a52743843b.png)

**Comment by kelno** [comment]
Will close for now
