### ISSUE TITLE
[#344] Sunseeker Geomancer's are not making their flowers change elements

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#589]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:21 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/344_

----

**Current behavior:**

Sunseeker Geomancer's are not making their flowers change elements

**Expected behaviour:**

They should cast aoe elemental spells on the flowers to make them change

**Steps to reproduce the problem:**

1. Watch a Sunseeker Geomancer

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

![image](https://user-images.githubusercontent.com/45530324/52714542-db9c9880-2fe5-11e9-97a0-03d86cb38f08.png)

https://www.youtube.com/watch?v=UaC8ZY1C6ag - 3:51 (in the background) another element cast at 4:06; can see the blood elf casting magic on the flower to make them change like the flower boss does later on

https://db.excalibur.ws/?npc=21574

**Comment by Jerrythemagicdog** [comment]
**Forms for the Frayers (flowers):**
Fire Form
http://tbc.cavernoftime.com/spell=34203
Frost Form
http://tbc.cavernoftime.com/spell=34202
Shadow Form
http://tbc.cavernoftime.com/spell=34205
Arcane Form
http://tbc.cavernoftime.com/spell=34204
Need to find appropriate transformation spells for the Geomancers (on the video they're seen to be casting Blizzard for example.)

**Comment by kelno** [comment]
Fixed with https://github.com/kelno/sunstrider-scripts/commit/5d9e850aea4a100facbf63fe848e00509b76c0df
