### ISSUE TITLE
[#358] Voidwalker's summoned by Grandmaster Vorpil move too quick

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#601]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:57 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/358_

----

**Current behaviour:**

Voidwalker's summoned by Grandmaster Vorpil move too quick

**Expected behaviour:**

They should be pretty slow which allows players to kill them before they get to the boss

**Steps to reproduce the problem:**

1. Fight Grandmaster Vorpil 
2. Let him summon voidwalkers
3. Watch them move way too fast

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

https://db.excalibur.ws/?npc=18732

https://www.youtube.com/watch?v=1zn538fRQ98

![image](https://user-images.githubusercontent.com/45530324/52716305-3506c680-2fea-11e9-9305-6c03a1ff26c2.png)

**Comment by Kaziner** [comment]
@kelno Marked as Question but I don't think it was imported to this group. 

I recall it being something about their speed which should be answered below.

https://www.youtube.com/watch?v=1zn538fRQ98 - 13sec in

**Comment by kelno** [comment]
Indeed the comment was lost here

**Comment by kelno** [comment]
Fixed with 10527
