### ISSUE TITLE
[#360] [Paladin] Consecration incorrect damage model

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#603]
<a href="https://github.com/plutonium447"><img src="https://avatars0.githubusercontent.com/u/40911527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [plutonium447](https://github.com/plutonium447)**
_Thursday Feb 14, 2019 at 05:58 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/360_

----

_breathes in_
**Current behaviour:**
The current calculation for the paladin spell Consecration is not accurate and does not correctly apply damge bonuses to its effect.
This causes the spells damage to not increase regardless of how much additional spell power stats are applied to the paladin.

(Consecration rank used = rank 6)
In fig 1. you can see the base damage per tick of the spell which is 64. The total damage cause by Consecration is 512 at this base.
In fig 2. you can see that even with spell power item equiped there is no change to the tick damage and this total damage
In fig 3. it is demonstrated that the process of applying flat bonuses to the spells ticks works correctly. Flat bonuses provided by librams/relics/etc are not affected by spell coefficients. This behaviour is blizzlike on vanilla versions of the game. Not sure about TBC but i would assume the same behaviour.
In fig 4. you can see that a set bonus has correctly applied its effect to the spell, changing the 64 damage per tick to 70 damage per tick.

However, fig 2,3,4 are incorrect and should be calculated differently

![screenshot from 2019-02-14 15-02-54](https://user-images.githubusercontent.com/40911527/52764701-e9e1c780-306c-11e9-9720-2f9b617b2e28.png)
fig 1. _base_

![screenshot from 2019-02-14 15-01-23](https://user-images.githubusercontent.com/40911527/52764723-fd8d2e00-306c-11e9-8d97-9b634affe7d1.png)
fig 2. _with spell power_

![screenshot from 2019-02-14 15-01-44](https://user-images.githubusercontent.com/40911527/52764729-03830f00-306d-11e9-8d56-997a0a1cddf5.png)
fig 3. _with a libram bonus_

![screenshot from 2019-02-14 15-06-43](https://user-images.githubusercontent.com/40911527/52764750-0da50d80-306d-11e9-85ca-b8f462063f1a.png)
fig 4. _with a set bonus_

**Expected behaviour:**
Consecration should scale its damage by a coefficient of 33% from total spell power. I found difficulty in finding a concrete source that describes the precise calculation for consecration, however there are no patchnotes or any evidence showing that the method of calculation was changed from 1.12 -> 2.4.3

![screenshot from 2019-02-14 15-54-05](https://user-images.githubusercontent.com/40911527/52765769-cfa9e880-3070-11e9-91aa-4b7ae99dc868.png)

As a result, i believe the correct coefficient is 33% and that below is the calculation method:

If the spell base of consecration is 512 damage, and the players spell power is 486, then the total damage caused by the spell will be 674, as: 

Base + ( SP * Cof ) = Total
512 + ( 486 * (1/3)) = 674

This results in tick damage per second of 84 damage, as:

Damage / 8 Seconds = Tick Damage per second
674 / 8 = 84

**Steps to reproduce the problem:**

1. Be a paladin
2. Cast consecration with bis sp gear
3. cry when you're still hiting garbage dps

**rev. hash/commit:** 
[15:44] Sunstrider rev. **10455** (aaf72e209219) 2019-02-13 12:14:05 +0100 (master branch) (Unix, DEBUG, Static) 
[15:44] Players online: 1 (Max: 7, Queued: 0) 
[15:44] Server uptime: 17 Hour(s) 58 Minute(s) 30 Second(s). 
[15:44] Smoothed update time diff: 50. 
[15:44] Instant update time diff: 51. 
[15:44] Current map update time diff: 2.

NOTES: 
[spell] Consecration (Rank 6) (27173) http://db.hellfire-tbc.com/?spell=27173
[item] Libram of the Eternal Rest (27917) http://db.hellfire-tbc.com/?item=27917
[effect] Improved Consecration (38422) http://db.hellfire-tbc.com/?spell=27173

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Thursday Feb 14, 2019 at 09:53 GMT_

----

Test comment

**Comment by kelno** [comment]
<a href="https://github.com/plutonium447"><img src="https://avatars0.githubusercontent.com/u/40911527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plutonium447](https://github.com/plutonium447)**
_Thursday Feb 14, 2019 at 10:27 GMT_

----

what is this sorcery

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Thursday Feb 14, 2019 at 13:31 GMT_

----

Shh, you were my test subject. You've seen nothing *waves hand*

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Thursday Feb 14, 2019 at 13:35 GMT_

----

Btw thank you for the very precise issue that's a developer wet dream

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Thursday Feb 14, 2019 at 13:36 GMT_

----

You can usually find correct spell ratios in DrDamage addon

**Comment by Jerrythemagicdog** [comment]
Fixed in 10491
