### ISSUE TITLE
[#363] [Blood Furnace Heroic] Laughing Skull Enforcer 

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-issues#606]
<a href="https://github.com/Paralol"><img src="https://avatars3.githubusercontent.com/u/4516769?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Paralol](https://github.com/Paralol)**
_Thursday Feb 14, 2019 at 10:58 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/363_

----

**Current behaviour:**

Laughing Skull Enforcer in Heroic Blood Furnace hitting excessively hard.
![image](https://user-images.githubusercontent.com/4516769/52782460-da797300-309a-11e9-943b-8560f6ec0a19.png)

**Expected behaviour:**

Unable to find exact damage numbers but a suitably geared tank shouldn't be dead in 2 simultaneous hits.

**Steps to reproduce the problem:**

1. Set dungeon difficulty to heroic
2. .tele bloodf
3. Attack first 2 Laughing Skull Enforcer and die quickly

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/52782639-4b208f80-309b-11e9-9113-f19ea8b21097.png)

**Comment by soup1234** [comment]
Checked, they're meant to hit between Damage: 742 - 1.1k
Walked in and got hit by about 10-11k on cloth

**Comment by kelno** [comment]
Fixed recently with the Shattered Halls rework
