### ISSUE TITLE
PUT HIM BACK RIGHT NOW

### ISSUE THREAD

**Issue by plutonium447** [ValorenWoW/sunstrider-issues#614]
**Current behaviour:**
HOW DARE YOU TOSS ABOUT A POOR HELPLESS GNOME HE DID NOTHING WRONG BUT HELP PLEBS WITH THEIR FLIGHTPOINTS

![screenshot from 2019-02-15 12-54-36](https://user-images.githubusercontent.com/40911527/52831771-97161780-3121-11e9-88d4-582b10fec9f7.png)

**Expected behaviour:**
HE NEEDS TO GO BACK WHERE HE BELONGS RIGHT NOW
@ 42.9, 85.0 IN EPL

**Steps to reproduce the problem:**

1. GO TO EPL
2. WHERE IS THE FLIGHTMASTER
3. OH THERE HE IS

**rev. hash/commit:** 
Sunstrider rev. 10470 (e53d6cfe1130) 2019-02-15 01:13:38 +0100 (master branch) (Unix, DEBUG, Static)

[npc] Bibilfaz Featherwhistle (12596) http://db.hellfire-tbc.com/?npc=12596

**Comment by plutonium447** [comment]
UNIDENTIFIED FLYING OBJECT SIGHTED
ALTITUDE: HIGH AS A KITE
VECTOR: NWN
SPEED: NEVER SEEN ON THIS MORTAL PLANE
![screenshot from 2019-02-15 13-08-10](https://user-images.githubusercontent.com/40911527/52832161-12c49400-3123-11e9-95ab-40b5f7920afa.png)

**Comment by plutonium447** [comment]
TARGET IS REACHING ESCAPE VELOCITY
![screenshot from 2019-02-15 13-11-47](https://user-images.githubusercontent.com/40911527/52832237-69ca6900-3123-11e9-8bc1-91d059e038aa.png)

**Comment by plutonium447** [comment]
KEK

**Comment by kelno** [comment]
He shouldn't have any waypoints?

**Comment by plutonium447** [comment]
nah he is a stationary npc that should be at coords 42.9, 85.0
standard flightmaster npc

**Comment by plutonium447** [comment]
put some lead boots on him and you should be g2g

**Comment by kelno** [comment]
Fixed with 10473
