### ISSUE TITLE
Warrior Charge not instantly AA'ing?

### ISSUE THREAD

**Issue by kakarotkaruma** [ValorenWoW/sunstrider-issues#616]
**Description:**

Whenever I charge as a warrior there is a very long delay before the first auto attack goes off. Not sure if this is intended in TBC or not

**Current behaviour:**

No instant AA on charge for warriors

**Expected behaviour:**

When charge goes off usually there is an instant attack, or it's possible to queue up a heroic strike. This has not been happening.
--->

**Comment by Jerrythemagicdog** [comment]
Confirmed, it's as if your swing timer is not ready, maybe is reset by Charge. 
Tried on dummies and random world creatures, same behavior.

**Comment by kelno** [comment]
Fixed with 10495
