### ISSUE TITLE
[Paladin] Redemption talent appears bugged from trainer

### ISSUE THREAD

**Issue by Septimush** [ValorenWoW/sunstrider-issues#618]
**Description:**

Was unable to learn Redemption Rank 1 from Ironforge trainers Brandur Ironhammer

**Current behaviour:**

Returned to trainer and I'd had learnt ranks 2, 3 and 4 in my Spellbook without manually learning/purchasing them

**Expected behaviour:**

Each rank should be purchased individually

**Steps to reproduce the problem:**

1. Speak to Paladin trainer in Ironforge
2. See spells available for purchase
3. Redemption Rank 1 will be green/purchasable, upon clicking will stay green/not learnt
4. Click off trainer
5. Click back to trainer, Redemption Rank 5 will be unavailable (as it should be)
6. Check Spellbook and Ranks 2, 3 and 4 are available but not Rank 1

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

Sunstrider rev. 10470 (ee53d6cfe1130) 2019-02-15 01:13:38 +0100 (master branch) (Unix, DEBUG, Static)

If you're testing on the public server, do a `.server info` in game and copy/screenshot the first line.  
If compiling the server yourself, copy the first line of the `worldserver` output.  
For example: Sunstrider rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)

**Comment by Tamosheik** [comment]
Were rank 2 to 4 given as part of the spells pack?

Rank 1 is learned through a race specific class quest chain. The first quest in each chain is listed below:
Draenei: [Quest.ID #10366]
Dwarf: [Quest.ID #1646]
Human: [Quest.ID #1642]
Blood Elf: [Quest.ID #9677]

**Comment by artieau** [comment]
Yes they are given from the Instant 58 pack, a relog can fix the issue too.
Otherwise  it is per Tamo above, needs the quest normally.
