### ISSUE TITLE
Quest "Unraveling the Mystery" wrongly repeatable

### ISSUE THREAD

**Issue by oj449** [ValorenWoW/sunstrider-issues#621]
**Description:**
quest is repeatable when it shouldn't be
**Current behaviour:**
Quest: Unraveling the Mystery can be repeated endlessly, giving xp each time instead of continuing questline into The Calling
**Expected behaviour:**
Quest should not pop back up when handed in, one time quest, should update quest data to open second in questline The Calling
**Steps to reproduce the problem:**

1. start quest
2. finish quest
3. go back to quest giver and can redo quest, handin npc does not give part 2 of questline.

**Comment by kelno** [comment]
Can you please provide quest id and npc id here?

**Comment by artieau** [comment]
Quest ID 8314
From NPC ID 15170

**Comment by kelno** [comment]
ty

**Comment by Jerrythemagicdog** [comment]
Fixed in 10489
