### ISSUE TITLE
charges are consuming main hand AA timer

### ISSUE THREAD

**Issue by oj449** [ValorenWoW/sunstrider-issues#622]
**Description:**
charge and intercept are consuming main hand auto attack timer, potentially other charges
**Current behaviour:**
Charge is eating your aa timer for mainhand, offhand still hits right away

**Expected behaviour:**
charge should not eat your main hand timer

**Steps to reproduce the problem:**
1. charge a mob
2. watch as only your offhand hits the enemy in the first window of attacks, or use a 2h to see no attacks for 3+ seconds.

**Comment by Jerrythemagicdog** [comment]
In the future please post it in the other issue you made ( https://github.com/ValorenWoW/sunstrider-issues/issues/616 ) as it's part of the same bug that you initially reported.

**Comment by kelno** [comment]
Fixed with 10495
