### ISSUE TITLE
[Shaman] Totemic Call double proc

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#624]
Description:

Totemic Call is providing more mana than it should, via a second proc.

Current behaviour:

When player uses Totemic Call (SpellID 36936), the player receives back 25% of  totem mana cost x 2 procs.

Expected behaviour:

It should only grant mana back once, one proc.

Steps to reproduce the problem:

Step 1 - Drop a totem such as Tremor Totem (SpellID 8143) which costs 60 mana.
Step 2 - Use Totemic Call 
Step 3 - Notice that player receives 2 x proc of 15mana back (25% of 60 mana totem)

![image](https://user-images.githubusercontent.com/40563134/52848746-97370700-3163-11e9-8581-43417c2d0943.png)

rev. hash/commit:

![image](https://user-images.githubusercontent.com/40563134/52848764-a322c900-3163-11e9-811c-2f7b5e50d4bd.png)

**Comment by kelno** [comment]
Fixed with 10493
