### ISSUE TITLE
[Shaman] Totemic Call using base mana cost

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#625]
Description:

The calculation for 25% mana return from Totemic Call is using the base spell, even if the player has reduced mana cost talents.

Current behaviour:

Totemic Call (Spell ID 36936) is returning 25% of the base mana of the totem - before the application of talent Totemic Focus (example 5 points is Spell ID 16225)

Expected behaviour:

Totemic Call should return 25% of the mana required to cast each totem.
That means after the cost discount talent such as Totemic Focus.

Steps to reproduce the problem:

Step 1 - Drop a totem such as Tremor Totem (Spell 8143) which costs 60mana before discount, and 45mana after talent discount.
Step 2 - Use Totemic Call
Step 3 - Have 15 mana returned to player instead of 11mana.

rev. hash/commit:

![image](https://user-images.githubusercontent.com/40563134/52849648-a15a0500-3165-11e9-99d8-27e768bed9b3.png)

**Comment by kelno** [comment]
It makes sense, but how are you sure that not blizzlike though?

**Comment by Jerrythemagicdog** [comment]
wowwiki:
> Keep in mind that Totemic Recall uses the base mana cost of your totems. For example Searing totem with normal cost returns 'x' mana when using Totemic Recall. If you have Mental quickness 3/3 and Totemic Focus 5/5, the same amount 'x' is returned.
