### ISSUE TITLE
demounting on any building related surface

### ISSUE THREAD

**Issue by oj449** [ValorenWoW/sunstrider-issues#626]
**Description:**
when you touch any building related surface you demount
**Current behaviour:**
touching any building related surface whilst mounted, say the moonpool in silithus, cenarion hold, or the tent near it, even though it is outside or just a bit of cloth on the outside of the tent, you will demount.

**Expected behaviour:**
that you only demount when going inside a building, or certain cave entrances.

**Steps to reproduce the problem:**
1. mount up
2. touch a building related object, most seem to work, you will notice that a large number of things will demount you that definitely should not.

**Comment by kelno** [comment]
Thanks!
Can you provide more specific examples beside the moonwells?

**Comment by oj449** [comment]
the inn that is there is demounting you which wasn't happening in the vanilla client,
randomly, the blocks in zul'farrak will demount you
as soon as you touch the ramp for a building that leads into it but is not "under cover" it should not demount you but it does for certain buildings, like the ones in silithus.
it doesn't seem to be a particular building bug but more of a total bug throughout building code

**Comment by oj449** [comment]
with this knowledge i'd say the huts inside of warsong gulch, as soon as you scrape the outside of them you should demount if this is the current building code.

**Comment by kelno** [comment]
Thanks.
Yes, I'm not looking to fix specific buildings it's just that I need specific cases we're sure are wrong, to investigate.

**Comment by kelno** [comment]
Fixed with 10488
