### ISSUE TITLE
Find Herbs/Minerals causes nodes to sparkle

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#630]
**Description:**

Find Herbs/Minerals causes nodes to sparkle like they are a killed mob with loot on it.
Perhaps a tracking issue.
Find Herbs Spell ID  2383
Find Minerals Spell ID 2580

**Current behaviour:**

Using Find Herbs causes nearby Herb nodes to sparkle
The same happens for Find Minerals

**Expected behaviour:**

They should not sparkle like they are a vampire from Twilight.
They should just be themselves, normal nodes.

**Steps to reproduce the problem:**

1. Step 1 - Use Find Herbs
2. Step 2 - Notice  herb nodes are sparkling
3. Step 3 - Change to Find Minerals
4. Step 4 - Notice mineral nodes are sparkling

![image](https://user-images.githubusercontent.com/40563134/52893865-2ccea700-31f5-11e9-8b2a-bb8323125563.png)
![image](https://user-images.githubusercontent.com/40563134/52893872-3fe17700-31f5-11e9-8c90-03ba4366d399.png)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52893877-4bcd3900-31f5-11e9-83d4-f8dbf46b620f.png)

**Comment by qoth** [comment]
I believe this is correct.
From 2.3.0 - Game objects that you can interact with will now sparkle and display their name over the object to make them more obvious. https://wow.gamepedia.com/Patch_2.3.0

and this wowhead thread from 2.3.0 - 'They only sparkle when you have Find Herbs on.'
https://www.wowhead.com/forums&topic=5359

**Comment by artieau** [comment]
Good find, I stand corrected!
