### ISSUE TITLE
Stealth in kitty broken? 

### ISSUE THREAD

**Issue by emorelix** [ValorenWoW/sunstrider-issues#633]
**Description:**

I can be seen in pvp in kitty stealth from very long range.

**Current behaviour:**

I get seen in stealth in kitty form from 30 yards from a target (tested on a lvl 60 warrior, i was 58) (Also borg has informed me he can see stealthed targets in silithus from 30+ yards too, he is a 60 orc warrior)

**Expected behaviour:**

I should not be seen from this distance so easily.

**Steps to reproduce the problem:**

This should not be the case in pvp. Have not tested this in pve yet. Maybe the stealth detection in pvp is set to lvl 70 awareness?

I was being charged at 30 yards away while in kitty stealth. This was when i am standing in the targets frontal visual cone.

![wowscrnshot_021619_144551](https://user-images.githubusercontent.com/47015256/52894348-0f510b80-31fc-11e9-8f6d-1e9c01c4526b.jpg)

**Comment by kelno** [comment]
Did you have the stealth talent here ?

**Comment by zemfi** [comment]
Even without full points in Feral Instinct (Harder to detect while prowling), he shouldnt be able to see the druid stealthed that far away, and you would be able to get in alot closer without being detected.

**Comment by Desparto** [comment]
![image](https://user-images.githubusercontent.com/26176852/53230219-521e5200-36da-11e9-88db-d3dea0708997.png)

Yeah I can be seen from this distance in stealth right now as a rogue. No way is this correct.

**Comment by kelno** [comment]
Closed and continuing on https://github.com/ValorenWoW/sunstrider-issues/issues/798
