### ISSUE TITLE
flightmaster chillwind

### ISSUE THREAD

**Issue by Sebbyyy** [ValorenWoW/sunstrider-issues#635]
**Description:**

no flightmaster at chillwind point wpl

**Current behaviour:**

above

**Expected behaviour:**

above

**Steps to reproduce the problem:**
walk to chillwind point, look

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by plutonium447** [comment]
related to issue #614 
https://github.com/ValorenWoW/sunstrider-issues/issues/614#issuecomment-464014747

this issue has been resolved in a future version. the server has not been updated yet
