### ISSUE TITLE
[Magtheridon] Hellfire Channeler - Soul Transfer not stacking.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#637]
**Description:**

Hellfire Channelers (17256) cast a buff called Soul Transfer (30531) on death that should stack on other Hellfire Channelers. Currently the buff is applied on death but does not stack.

**Current behaviour:**

Currently it does not stack on other Hellfire Channelers.

**Expected behaviour:**
It should stack.

**Steps to reproduce the problem:**

1. Kill a Hellfire Channeler during the encounter
2. Soul Transfer gets applied on its ally channeler
3. It doesn't stack up

> Soul Transfer: When one Channeller dies, all surviving Channellers gain this stacking buff, increasing size by 20% and damage and casting speed by 30% (with four buffs, the last Channeler has 220% cast speed) 

https://wowwiki.fandom.com/wiki/Magtheridon_(tactics)

**rev. hash/commit:** 
10489

**Comment by kelno** [comment]
Related https://github.com/TrinityCore/TrinityCore/issues/22272

**Comment by Jerrythemagicdog** [comment]
Fixed
