### ISSUE TITLE
[Creature] Duskbats in Tirisfal Glades are evading

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#638]
**Description:**
All Duskbats (entry 1512) are evading in Tirisfal Glades. When attacked the creature immediately starts evading and continues random movement. It does not fight the player back and is unkillable by low level players.

**Steps to reproduce the problem:**
Make an Undead character

Go out of the tomb

Attack a Duskbat

**rev. hash/commit:** 
10500

**Comment by kelno** [comment]
FIXED

**Comment by kelno** [comment]
Server is ready for release
