### ISSUE TITLE
[Druid] Tree of Life bonus healing aura for party members not applying

### ISSUE THREAD

**Issue by LoshyFirestorm** [ValorenWoW/sunstrider-issues#641]
**Issue**
While in Tree of Life form, there is meant to be a bonus to the healing received by all party members in 45 yards by 25% of your total spirit applied via an aura named Tree of Life (Spell ID: 34123) that is currently not being applied.

**Description:**

While in Tree of Life, the druid is meant to increase the healing of all party members within 45 yards based on their spirit.  This occurs as a separate aura-like buff by the name of Tree of Life.  The Spell ID for this aura is 34123 and has the same icon as Tree of Life.

**Current behaviour:**

While in Tree of Life form, the form does not apply the increased healing received aura to party members (nor yourself).

**Expected behaviour:**

While in Tree of Life form, the form should grant the aura Tree of Life (Spell ID 34123) to yourself and other party members, increasing healing received equal to 25% of the druids spirit.

**Steps to reproduce the problem:**

1. Step 1: Enter Tree of Life Form
2. Step 2: Be in a party with someone nearby (to confirm both it not applying to yourself or party members)
3. Step 3: Cast Rejuvenation on yourself and ally while in form (to get base healing amount)
4. Step 4: Drop Tree of Life, cast Rejuvenation after it has dropped, and see the same healing amount. (Just to prove it is not applying at all and is not just hidden)

**rev. hash/commit:** 

Sunstrider rev. 10500 2019-02-17 12:04:42 +0100 (master branch) (Unix, DEBUG, Static) 
![revision](https://user-images.githubusercontent.com/43313533/53004781-96f97d00-347d-11e9-8dc7-cfdf9a9a5f23.png)

**Comment by kelno** [comment]
Fixed in 10521
