### ISSUE TITLE
Flight hax in Azeroth

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#644]
**Description:**

Able to swim/fly in the air in Azeroth after leaving Outlands

**Current behaviour:**

When leaving Outlands on a flying mount to Azeroth, the player dismounts however remains in 'swim' or 'fly' mode/animation. Can then swim around in the air in Azeroth.

**Expected behaviour:**

Should not be able to fly at all in Azeroth, once zoned over player should be forced to ground with many gravity.

**Steps to reproduce the problem:**

CHANGEME
1. Be on flying mount such as Ashes of Al'ar in Outlands (such as on Outlands side of Dark Portal)
2. Fly through the Dark Portal to Blasted LAnds
3. Swim through air

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53165177-26da2b00-3626-11e9-87dd-84167b67aa63.png)

**Comment by kelno** [comment]
Fixed with 10535
