### ISSUE TITLE
[Shaman] Natures Swiftness not being consumed on use

### ISSUE THREAD

**Issue by Harrock1** [ValorenWoW/sunstrider-issues#645]
**Description:**

Natures Swiftness talent is not being consumed when casting spells. Buff is permanent until death.

**Current behaviour:**

Using natures swiftness gives a permanent buff instant cast spells that is only consumed on death. Cooldown is started when you die.

**Expected behaviour:**

Natures swiftness should be consumed on next spell with cast time less than 10 seconds, causing it to be instant.

**Steps to reproduce the problem:**

1. Talent a shaman with NS
2. Activate it
3. Spam chain heals

**rev. hash/commit:** 
![rev](https://user-images.githubusercontent.com/25610698/53168326-80465800-362e-11e9-8a3d-6643c293a302.JPG)

**Comment by kelno** [comment]
Fixed with 10532
