### ISSUE TITLE
Druid - moonglade TP

### ISSUE THREAD

**Issue by emorelix** [ValorenWoW/sunstrider-issues#647]
**Description:**

No TP - Moonglade in my spellbook on 70 druid

**Current behaviour:**

No teleport: Moonglade spell in spellbook on a lvl 70 boosted druid 

**Expected behaviour:**

Meant to be in spellbook

**Steps to reproduce the problem:**

1: add it to game?

=

**rev. hash/commit:** 

pics attached

**Comment by emorelix** [comment]
![wowscrnshot_022219_010506](https://user-images.githubusercontent.com/47015256/53174447-ee464b80-363d-11e9-9838-ff2c16d2a884.jpg)
![Uploading WoWScrnShot_022219_010510.jpg…]()

**Comment by emorelix** [comment]
![wowscrnshot_022219_010510](https://user-images.githubusercontent.com/47015256/53174485-08802980-363e-11e9-8b5a-cca4b49553f7.jpg)

**Comment by Jerrythemagicdog** [comment]
I believe this spell is taught by a trainer and missed in the Helper NPC spells he's teaching. Please check with a Druid Trainer in any city.

**Comment by emorelix** [comment]
Went to druid trainer in Thunderbluff. Learnt tangling roots and insect swarm ranks, but there was no Teleport: Moonglade. =/

**Comment by zemfi** [comment]
Can confirm its not on any alliance trainers either. (18960 / 19027)

.rev 10530

**Comment by artieau** [comment]
It is taught via a quest chain at Level 10.
For alliance it is Quest ID 5921
Breadcrumb from earlier zone such as Dolanaar
