### ISSUE TITLE
[Spell] Molten Armor 

### ISSUE THREAD

**Issue by Soopra** [ValorenWoW/sunstrider-issues#652]
Molten armor returning 500-600 damage back per attack, scaling incorrectly off spell power 

reproduce; get mage with gear, put molten armor on, get a rogue to hit you in a duel
rogue dies without mage attacking.

**Comment by kelno** [comment]
Please include spells ids and precise setup:
How many spell power for your 500-600 damage?
No talents for the mage?

**Comment by Soopra** [comment]
579 damage
no talents at all (fresh 70, talents reset) 
spell ID is 30482
uploading video now

**Comment by Soopra** [comment]
https://www.youtube.com/watch?v=onnBsSCwMzs&feature=youtu.be

**Comment by Soopra** [comment]
![molten](https://user-images.githubusercontent.com/29525708/53236950-99600f00-36e9-11e9-8975-72a3d58890c4.jpg)

**Comment by Fapsalad143** [comment]
Hey team, just adding to the pile here from my experience regarding molten armor 

![wowscrnshot_022319_000428](https://user-images.githubusercontent.com/47891406/53244538-4a24d900-36ff-11e9-9ae1-3d293bb034da.jpg)

**Comment by BarrensJerk** [comment]
It was proccing 77 damage when naked but still with talents, so its probs on the spot with what the tooltip describes, 75 damage to attackers, only scaling with spellpower

**Comment by woiwoz** [comment]
Fixed completion, waiting for merger

**Comment by kelno** [comment]
Fixed with 10537
