### ISSUE TITLE
[Druid] Cure Poison / Abolish Poison

### ISSUE THREAD

**Issue by zemfi** [ValorenWoW/sunstrider-issues#653]
**Description:**

Both Abolish Poison & Cure Poison spells are available, when only Abolish Poison is the correct druid spell (cure poison is a shaman spell).

**Current behaviour:**

Check your spellbook (resto tree), and you see both spells.

**Expected behaviour:**

Cure Poison spell needs to be removed.

Druid: Abolish Poison (#2893)
Shaman: Cure Poison (#526)

![tbc_poison](https://user-images.githubusercontent.com/46832429/53235961-38373c00-36e7-11e9-8126-a97eb74f0c7e.jpg)

.rev 10530

**Comment by Jerrythemagicdog** [comment]
It is a Druid spell acquired from a quest line: https://wow.gamepedia.com/Cure_Poison .

"Many druid players do not do the quest chain to acquire this spell since it is replaced quickly by [Abolish Poison]."
