### ISSUE TITLE
[Mage] Scorch (27074) and Improved Scorch (12873)

### ISSUE THREAD

**Issue by BarrensJerk** [ValorenWoW/sunstrider-issues#654]
**Description:**

Fire mages with Improved Scorch 3/3 have 100% chance of applying debuff 22959 Fire Vulnerability

**Current behaviour:**

When 2 mages with 3/3 improved scorch are scorching the same target, the debuffs are overwriting one another rather than adding stacks. Mage 1 adds a single stack of fire vulnerability, mage 2 scorches and overwrites that single stack with their own. After second stack of debuff 22959 is added mage who added it can stack to 5 without debuff being overwritten by other mage. Then same mage is the only one that can refresh the debuff, rather than any mage.

**Expected behaviour:**

Multiple mages scorch simultaneously or near simultaneously, and a single collated Fire Vulnerability debuff should exist for them all, for any mage to be able to add to stack up to 5.

**Steps to reproduce the problem:**

1. Have 2 mages with 3/3 improved scorch scorch target simultaneously. Debuff gets pushed off by each others scorch rather than stacking, until one mage lands more than two in a row to establish 2 stacks, then it wont get pushed off by single scorch from mage 2.

**rev. hash/commit:** 

Sunstrider rev. 10530 (ec8fa6ac1145)

**Comment by kelno** [comment]
Fixed with 10589
