### ISSUE TITLE
[Shaman] Windfury Totem sometimes attacks itself on summon

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#657]
**Description:**
Sometimes lower ranks of Windfury Totem attack itself on summon

> Windfury Totem II's gains 1 extra attacks through Windfury Totem.
> Windfury Totem II's melee swing hits Windfury Totem II for 34 Physical.

Spell ID for rank 2: 10613

So far it happened for ranks 1 (10610), 2 (10613) and 3 (10614) of the spell.

**Expected behaviour:**

It should not attack itself.

**rev. hash/commit:** 
Sunstrider rev. 10533 (cf4f6bcdef22) 2019-02-22 15:51:09 +0100 (master branch)

**Comment by kelno** [comment]
Fixed with 10559
