### ISSUE TITLE
[Mechanic] "Block" can fully block damage, should only be able to do it partially

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#659]
**Description:**
Currently blocking damage allows to fully block the damage sometimes (seems to be 100% on normal creature / boss attacks and only partial blocks on special attacks like Cleave). 

**Expected behaviour:**

In TBC we should not be able to Block damage fully. Block Value gives us the amount of the damage we are going to mitigate by blocking an attack. 

https://wow.gamepedia.com/Block_value
https://wow.gamepedia.com/Block
https://www.wowhead.com/forums&topic=41099#p398634

**rev. hash/commit:** 

Sunstrider rev. 10535

**Comment by kelno** [comment]
Fixed with 10536
