### ISSUE TITLE
[Warrior] Retaliation (20230) issue

### ISSUE THREAD

**Issue by Hoochsex** [ValorenWoW/sunstrider-issues#661]
Description:

Retaliation (20230) is currently damaging the warrior when changing stances.

Current behaviour:

![image] https://user-images.githubusercontent.com/45529944/53273213-1d90b180-373f-11e9-86fa-186a84453be2.png

When swapping stances while affected by Retaliation (20230) the warrior hits itself.
 

Expected behaviour:

This should not damage the warrior 

Steps to reproduce the problem:

CHANGEME

Step 1: Use Retaliation (20230) 
Step 2: Swap to any other warrior stance
Step 3: Cry

rev. hash/commit:

CHANGEME

![image] https://user-images.githubusercontent.com/45529944/53273794-af4cee80-3740-11e9-9189-163f8d320668.png

**Comment by woiwoz** [comment]
Interesting question... I'll check him now.

**Comment by woiwoz** [comment]
fixd

**Comment by kelno** [comment]
Fixed with 10538
