### ISSUE TITLE
Hunter skills lost after relog - PTR

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#665]
**Description:**

Hunters on PTR lose some Pet abilities after they relog.
These spells are from the Level 10 quest series such as  Taming the Beast (6082).
Spells are taught via Taming Lesson - Spell ID 23356

**Current behaviour:**

New hunters on PTR are taught all relevant skills however player loses some from Taming Lesson  (23356) after a relog.
These include 
Tame Beast - 1515
Call Pet - 883
Dismiss Pet - 2641

**Expected behaviour:**

Spells should not disappear after relogging.

**Steps to reproduce the problem:**

CHANGEME
1.  Create Hunter on PTR
2. Boost to 58 or 70
3. Have your spells in your spellbook
4. Relog, check and those spells are gone.

This is likely related just to the Super Helper force learning spells that are via Quest -> Spell -> which learns other spells.

The Hunter has the spell 23356 in their spell book - which they should not have.
But using that spell does nothing.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53276470-3c00a800-3753-11e9-868d-e2bcbef9dc16.png)

**Comment by Jerrythemagicdog** [comment]
Similar thing happens to Warlock pets I believe and other abilities connected to a quest.

**Comment by kelno** [comment]
Does this still happen if you do the quest ?

**Comment by artieau** [comment]
I believe if you go back and do the quests, you keep the spells.
I can see someone tried to bypass this by adding the quest reward to the player - but that is not working.
Taming Lesson (23356) is the quest reward, that spell effect teaches the spells to the hunter.
From the 4 quests seen at https://classicdb.ch/?spell=23356

**Comment by drak41** [comment]
If you do the qst's you get the spells back, can confirm as I went and did the qst's and now have no issues with hunter or lock pets
