### ISSUE TITLE
[Shaman] Sentry Totem - Sight change doesn't work

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#668]
**Description:**

Right clicking Sentry Totem buff does not change your sight between Player and Totem.
Sentry Totem (Spell 6495)

**Current behaviour:**

When you right-click the buff on the player from Sentry Totem, your sight does not change.

**Expected behaviour:**

Right-clicking the buff should change your sight between totem and player locations each time.

**Steps to reproduce the problem:**

1. Drop Sentry Totem
2. Right-click the buff
3. Nothing happens

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53279213-95bc9e80-3762-11e9-8ad2-4afd91988939.png)

**Comment by woiwoz** [comment]
Fixed completion, waiting for merger

**Comment by kelno** [comment]
Should be fixed with 10556

**Comment by artieau** [comment]
Working <3
