### ISSUE TITLE
Warlock Pets don't re-summon after dismounting

### ISSUE THREAD

**Issue by Kaziner** [ValorenWoW/sunstrider-issues#669]
**Description:**

Warlock Pets don't re-summon after dismounting

**Current behaviour:**

Currently if I have a warlock pet summoned; when I mount up it disappears and when I dismount it doesnt re-appear

**Expected behaviour:**

If i had an active pet when I mounted up it should be summoned next to me when I dismount

**Steps to reproduce the problem:**

CHANGEME
1. Summon a warlock pet (voidwalker as an example)
2. Mount up (any mount will do)
3. Dismount; the pet will not return to your side requiring you to cast another summon voidwalker to get your pet back

Rev 10533

This is crippling for warlocks in open world as they rely on their pets for PvE and PvP content and will need to spend 6secs + >1k mana and a soul shard every time they want to mount up to do something.

https://www.youtube.com/watch?v=GJDWMCvu04A - Expected behavior seen at 4:27 mark on this video - as the warlock dismounts his succy appears next to him

**Comment by artieau** [comment]
This also happens with Hunter pets now as of Rev 10533

**Comment by Jerrythemagicdog** [comment]
https://github.com/kelno/sunstrider-core/commit/23e2038404e97ebe5331e6d49473e5dd46cc0d47

**Comment by artieau** [comment]
@Jerrythemagicdog @kelno @Kaziner 
https://www.youtube.com/watch?v=kiKmBnVZIjg
Start at 10:35
While mounted 'outdoors' this is in a BG though. Confirmed that player mounted does have pet be hidden.
Hunter dismount at 10:36 - watch the Call Pet spell at bottom right of screen is NOT used.
Pet visible moments later, spawns by itself.
Warlock opponent is mounted at 10:38, also has no pet visible.
Dismounts at 1:39 and Felhunter is suddenly visible.

**Comment by woiwoz** [comment]
fixd

**Comment by artieau** [comment]
fixed

**Comment by kelno** [comment]
Thanks Artie
