### ISSUE TITLE
[Warrior] Impale (16494) not working

### ISSUE THREAD

**Issue by Hoochsex** [ValorenWoW/sunstrider-issues#672]
Description:

After testing the warrior talent Impale (16494) it does not seem to be adding on 20% damage on critical strikes. I did 3 tests at 1000 weapon swings each that i will link below (all tests were done in Berserker Stance and while attacking the Boss target dummy in Stormwind with a 2hand on and 0 expertise)

Current behaviour:

Test 1) No talents in Impale or 2hand weapon spec https://cdn.discordapp.com/attachments/245105523593052160/548659121893670913/unknown.png

Test 2) 2x Talent points in impale https://cdn.discordapp.com/attachments/245105523593052160/548673962767286302/unknown.png

Test 3) 5x Talent points in 2hand weapon spec (was testing if the damage was being added, seems to be working, throwing this in cause another 1000 weapon swings) https://cdn.discordapp.com/attachments/245105523593052160/548705302288269362/unknown.png

Expected behaviour:

Impale - Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%. 

Steps to reproduce the problem:

Step 1: Attack a Boss dummy in Stormwind without Impale (16494) talented
Step 2: Attack a Boss dummy in Stormwind with impale (16494) talented
Step 3: Compare results

rev. hash/commit:

![image](https://user-images.githubusercontent.com/45529944/53281402-8abe3a00-3773-11e9-80b7-705d1729c973.png)

**Comment by woiwoz** [comment]
In my tests, this talent is not a problem. The expected behavior described by the talent only works for spell, not basic melee attacks.
