### ISSUE TITLE
Ogri'la Questing/faction Hub not added to game yet/missing.

### ISSUE THREAD

**Issue by soup1234** [ValorenWoW/sunstrider-issues#673]
**Description:**
Ogri'la Questing/faction Hub not added to game yet/missing.

CHANGEME Description of the problem or issue here.
No visible quest hub->> see screenshot provided

**Current behaviour:**
Nothing spawned.
Location: Blade's Edge Mountains. Vortex Pinnacle

**Expected behaviour:**
There should be a faction named Ogri'la that provide daily quests.

![ogila](https://user-images.githubusercontent.com/46829458/53281474-1e483880-377d-11e9-82f6-5d5da4814650.jpg)

![ogrila2](https://user-images.githubusercontent.com/46829458/53281502-931b7280-377d-11e9-9477-b2aeddae4171.jpg)

**Comment by artieau** [comment]
Was added in Patch 2.1
Server running at 2.0 content wise
https://wowwiki.fandom.com/wiki/Patch_2.1.0

**Comment by soup1234** [comment]
Thanks for the clarification.
