### ISSUE TITLE
Glancing blows do not seem to be working correctly

### ISSUE THREAD

**Issue by Hoochsex** [ValorenWoW/sunstrider-issues#674]
Description:

Whilst testing warrior talents on the Boss target dummy in Stormwind i noticed Glancing Blows are actually hitting harder then regular hits, 

Current behaviour:

The following screen shots have 1000 weapon swings each. https://cdn.discordapp.com/attachments/245105523593052160/548659121893670913/unknown.png https://cdn.discordapp.com/attachments/245105523593052160/548673962767286302/unknown.png

The last one was with 5% more damage from 2hand weapon spec in the arms tree. https://cdn.discordapp.com/attachments/245105523593052160/548705302288269362/unknown.png

Expected behaviour:

Post 2.1 Edit
The release notes for patch 2.1 say the following:

Glancing Blows have significantly less of a chance to occur during a player's melee attacks when targets are near the player's level.
The new formula seems to be:

glancing blow chance = 10 + mob defense - player weapon skill

For a level 73 mob, that's a 25% chance of glancing blow. 
Reference: https://wowwiki.fandom.com/wiki/Glancing_blow

Steps to reproduce the problem:

CHANGEME

Step 1: Auto attack a Boss dummy in Stormwind 
Step 2: Have a combat tracker like recount record the glancing blows

rev. hash/commit:

![image](https://user-images.githubusercontent.com/45529944/53281565-6748be80-3776-11e9-997f-1021dd7aeb81.png)

**Comment by kelno** [comment]
Fixed with 10566

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/19bd2e1b905ffbc7f91865856fb593388cbbb131
