### ISSUE TITLE
[Shaman] Windfury totem leads to players hitting themselves.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#676]
**Description:**
Windfury procs on players affected by the Windfury buff.

> Bighomie's melee swing hits Training dummy for 151 Physical. (Glancing)
> Bighomie's melee swing hits Training dummy for 140 Physical.
> Bighomie's melee swing hits Training dummy for 118 Physical. (Glancing)
> Bighomie's melee swing hits Training dummy for 144 Physical.
> Bighomie's melee swing hits Training dummy for 134 Physical.
> Bighomie's gains 1 extra attacks through Windfury Attack.
> Bighomie's melee swing hits Bighomie for 351 Physical.
> Bighomie gains Windfury Attack.
> Windfury Attack fades from Bighomie.
> Bighomie's attack misses Training dummy.

Similar thing happened to Hand of Justice before.

**Expected behaviour:**

Should not proc on the player.

**Steps to reproduce the problem:**

CHANGEME
1. Place a Windfury Totem
2. Hit a target
3. You will hit yourself sometimes when Windfury Procs

**rev. hash/commit:** 
Sunstrider rev. 10533 (cf4f6bcdef22) 2019-02-22 15:51:09 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by plutonium447** [comment]
![screenshot from 2019-02-23 21-55-17](https://user-images.githubusercontent.com/40911527/53286150-bb26c800-37b5-11e9-8ba5-4618c016750b.png)

**Comment by kelno** [comment]
Fixed with 10559
