### ISSUE TITLE
(Warlock) Nightfall not functioning as intended

### ISSUE THREAD

**Issue by Gyoz** [ValorenWoW/sunstrider-issues#681]
Current behaviour:
When nightfall procs during a shadow bolt cast the buff is consumed at the end of the current cast

Expected behaviour:
When procced during a spell cast it should allow the next shadowbolt after that to be an instant cast

Steps to re-produce:
1. Spec into nightfall
2. Cast corruption on dummy
3. Have nightfall proc mid-way through cast

IDs:
Shadowbolt Rank11: 27209
Nightfall Rank2: 18095

**Comment by kelno** [comment]
Fixed with 10590
