### ISSUE TITLE
[Paladin] Incorrect spell requirements

### ISSUE THREAD

**Issue by plutonium447** [ValorenWoW/sunstrider-issues#688]
**Description:**
Several paladin spells are not accessible due to impossible unmet learnt spell requirements. These include the spells:

- Blessing of Salvation
- Seal of Justice

![screenshot from 2019-02-24 21-57-40](https://user-images.githubusercontent.com/40911527/53298938-93e8fd00-3880-11e9-8cd7-19b0190280b0.png)
![screenshot from 2019-02-24 22-01-45](https://user-images.githubusercontent.com/40911527/53298940-1f15c300-3880-11e9-9d4b-922af908fa96.png)

**Current behaviour:**
These spells cannot be learnt or used by paladins

**Expected behaviour:**
These spells should not have these learnt spell requirements, only the minimum level requirements.

**Steps to reproduce the problem:**
1. create a paladin
2. use super helper to lvl up
3. notice no salv or justice seal
4. go to a pally trainer
5. discover you cant train the spells
6. ???
.7 dunno y i didnt report this eariler . im lazy

**rev. hash/commit:** 
Sunstrider rev. **10541** (2c9e67f6a401) 2019-02-23 12:10:30 +0100 (master branch) (Unix, DEBUG, Static

**notes**
[spells] Blessing of Salvation (1038)
[spells] Seal of Justice (20164)

thx and <3

**Comment by kelno** [comment]
Fixed with 10558

**Comment by alltyou** [comment]
this has not been properly fixed

**Comment by kelno** [comment]
On what server rev did you test that?

**Comment by plutonium447** [comment]
![screenshot from 2019-02-27 07-49-49](https://user-images.githubusercontent.com/40911527/53448926-5349d900-3a64-11e9-9e7b-3b89d7b4dad3.png)
this issue has been correctly fixed
<3 kelno
