### ISSUE TITLE
Looting in stealth (rogue)

### ISSUE THREAD

**Issue by emorelix** [ValorenWoW/sunstrider-issues#689]
**Description:**

Im able to loot targets when in stealth on my rogue

**Current behaviour:**

Im able to loot targets when in stealth on my rogue

**Expected behaviour:**

looting in stealth should Unstealth me

**Steps to reproduce the problem:**

Go stealth on rogue.
Loot a corpse.
Does not unstealth.

**rev. hash/commit:** 

see below
![wowscrnshot_022519_115403](https://user-images.githubusercontent.com/47015256/53308307-119a2080-38f4-11e9-8365-ba6ab5bbdd85.jpg)

**Comment by woiwoz** [comment]
fixd rev 10595
