### ISSUE TITLE
Server crash Chess event

### ISSUE THREAD

**Issue by qoth** [ValorenWoW/sunstrider-issues#693]
**Description:**

Chess event is causing server crash

**Current behaviour:**

Start chess event, wait 5 seconds, and server will crash

**Expected behaviour:**

Server should not crash

**Steps to reproduce the problem:**

CHANGEME
1. Control King Llane ( have not tested controlling horde pieces)
2. You will gain control of the piece and event will start
3. ~5 secs later server crashes

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/53310508-1dd6ab80-38fd-11e9-920d-96b7ab9a6d54.png)

**Comment by kelno** [comment]
Fixed with 10562
