### ISSUE TITLE
Interrupting channeled spells with another spell doesn't trigger GCD animation correctly.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#695]
**Description:**
Global Cooldown doesn't visually appear on the action bar and the character's hands visually glow as if he is going to cast the spell but it's only visual - it happens when casting another spell after a channeled spell (like Blizzard or using bandages. ) 
Here's a clip of how it looks: https://streamable.com/o1l3w

**Expected behaviour:**
Here's how it's supposed to look: https://streamable.com/x14pg
Notice the lack of glowing hands and GCD triggering properly on Arcane Explosion on the bars in comparison to the above example.

**Steps to reproduce the problem:**

1. Cast a channeled spell like Blizzard
2. Interrupt it by casting Arcane Explosion or other instant spell
3. The GCD doesn't trigger properly as seen in first example.

**rev. hash/commit:** 

rev. 10564

**Comment by kelno** [comment]
Fixed with 10588
