### ISSUE TITLE
[NPC] Bloodmaul Brute (19991)

### ISSUE THREAD

**Issue by BarrensJerk** [ValorenWoW/sunstrider-issues#698]
**Description:**

Bloodmaul Brute melee hitting and cleaving for a lot more damage than anticipated from a nonelite level 66 mob.

**Current behaviour:**

Bloodmaul Brute's Cleave hits Jerk for 3619 Physical.
Bloodmaul Brute's melee swing hits Jerk for 3051 Physical.
Your equipped items suffer a 10% durability loss.
Jerk died.
Jerk's Fire Blast hits Bloodmaul Brute for 1300 Fire.
Bloodmaul Brute's Cleave hits Jerk for 4217 Physical.
Your equipped items suffer a 10% durability loss.
Jerk died.

**Expected behaviour:**

Should hit for a lot less. Not sure exactly how much,, but not swinging for 3-4k

**Steps to reproduce the problem:**

1. Go to Blade's Edge
2. Pick a fight with a Bloodmaul Brute
3. Take a lot of damage

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

re. 10564

**Comment by BarrensJerk** [comment]
More mobs hitting like trucks:

Lashh'an Talonite (19943)
Lashh'an Windwalker (19945)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10568
