### ISSUE TITLE
Re gemming item makes unequipped 

### ISSUE THREAD

**Issue by nichanderson** [ValorenWoW/sunstrider-issues#699]
**Description:**

Replaced a gem in my gloves (Fel Leather Gloves; item ID=25685) and could not equip after stating "You cannot equip more than one of those."

**Expected behaviour:**

Should be able to replace gems in items

**Steps to reproduce the problem:**

Step 1: Create rogue and lvl to 70
Step 2: Gem Fel Leather Gloves
Step 3: Remove gloves off character and place in bag
Step 4: Place new gems into glove slots
Step 5: Try to equip gloves

![image](https://user-images.githubusercontent.com/21208563/53403142-cde00d80-39fe-11e9-8482-399c7c3904f7.png)

**Comment by Jerrythemagicdog** [comment]
Are those gems some of the heroic drop gems? There are some rules as to how many of the same type of heroic gem you can equip at the same time.

**Comment by nichanderson** [comment]
Yes that mush have been it then!
         [image: cid:image001.png@01D14A00.BC16EED0]


*Nicholas Anderson*
Research PhD Candidate
CQUniversity Australia, Building 361, Ibis Highway, North Rockhampton Qld
4701
*M *+61 438 871 360* | E **nicholas.anderson@cqumail.com
<nicholas.anderson@cqumail.com>*

This communication may contain privileged or confidential information. If
you have received this in error,

please return to sender and delete. CRICOS: 00219C | RTO Code 40939

**Comment by plutonium447** [comment]
nice email nick
