### ISSUE TITLE
All Mobs hitting hard

### ISSUE THREAD

**Issue by Smudgee** [ValorenWoW/sunstrider-issues#709]
**Description:**

Npc mobs are auto attacking for 2k+

Tested on about 5 different types of mobs, blades edge/netherstorm/nagrand

**Current behaviour:**
Mobs bending me over without lube. 

**Expected behaviour:**

Not being bent over by everything, or provide lube. 

**Steps to reproduce the problem:**

Approach random npc with a cheerful demeanor, get hit and die. 

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/45928493/53476331-3940e280-3ac6-11e9-8599-8993e773e990.png)

**Comment by kelno** [comment]
Please provide specifics examples here

**Comment by plutonium447** [comment]
.tele nagrand
go and attack one of the Aged Clefthoof in the area

this issue is popping up all over outland

**Comment by kelno** [comment]
Fixed with 10568
