### ISSUE TITLE
[NPC] Monster damage massively inflated.

### ISSUE THREAD

**Issue by LoshyFirestorm** [ValorenWoW/sunstrider-issues#710]
**Description:**

Many monsters in the open world have massively inflated damage.  This includes not only mobs in Outland, but Old World as well.  The following list is the current mobs I have found to do inflated damage:

Name: NPC ID
Blistering Rot: 16901
Blistering Ooze: 16903
Terrorfiend: 16951
Infernal Warbringer: 19261
Starving Helboar: 16879
Fel Handler: 19190
Netherhound: 16950
Wrathguard: 18975
Doomwhisperer: 18981
Collapsing Voidwalker: 17014
Subjugator Yalqiz: 19335
Vacillating Voidcaller: 19527
Bleeding Hollow Peon: 16907
Bleeding Hollow Grunt: 16871
Eye of Grillok: 19440
Bleeding Hollow Necrolyte: 19422
Bleeding Hollow Tormentor: 19424
Raging Collosus: 19188
Stonescythe Alpha: 16929

I will try to gather NPC's by zone and make new issues when they come up with the same damage inflation.

**Current behaviour:**

Monsters that should not be destroying players, such as level 58 helboars in Hellfire Peninsula, are doing as much as 2k per white swing.

**Expected behaviour:**

The monsters listed in the description should not be dealing as much damage as they should.  (Eye of Grillok dealing 17k for instance)

**Steps to reproduce the problem:**

1. Step 1: Find one of the listed monsters
2. Step 2: Get hit by it
3. Step 3: Realise normal monsters are hitting harder than some elites with white swings.

**rev. hash/commit:** 

![severinfo](https://user-images.githubusercontent.com/43313533/53478325-42c84b80-3ac2-11e9-8a9f-474429c1565d.png)

**Comment by kelno** [comment]
Thanks for the detailed report!
