### ISSUE TITLE
Warlock T6 2 Set scaling with spellpower

### ISSUE THREAD

**Issue by Harrock1** [ValorenWoW/sunstrider-issues#718]
**Description:**
2 Set T6 Malefic set bonus is appling current +healing 

**Current behaviour:**
Both Corruption and Immolate correctly applying Siphon Essence (spell=38394) to each tick but is using player +healing to caclulate value (instead of stated 70 health)

**Expected behaviour:**
Ticks should be 70 health per dot tick (both immolate and corruption can trigger this) and is only increased in healing via buffs on the warlock (amplify magic/fel armor)

**Steps to reproduce the problem:**

Pre-requisite: Equip any 2 pieces of item set 670
1. Step 1 Use +damage and healing trinket (or just + healing trinket)  
2. Step 2 Cast Corruption and Immolate onto a target dummy
3. Step 3 Note healing recieved

**Rev. hash/commit:** 

 Sunstrider rev. 10570 (2eecf786f40e) 2019-02-26 18:08:10 +0100 (master branch)

**Screenshots**

![2set1](https://user-images.githubusercontent.com/25610698/53548396-7c15bf80-3b85-11e9-8502-4812bbfe5e19.JPG)
![2set2](https://user-images.githubusercontent.com/25610698/53548402-7e781980-3b85-11e9-8d91-69c6a701847f.JPG)

**Comment by kelno** [comment]
Fixed
