### ISSUE TITLE
Noggenfogger Elixirs do not work

### ISSUE THREAD

**Issue by Harrock1** [ValorenWoW/sunstrider-issues#721]
**Description:**

Noggenfogger Elixir (8529) do not give buffs

**Current behaviour:**

Popping noggenfoggers does nothing, animation appears but no buff is applied (any of them)

**Expected behaviour:**

Noggenfogger Elixirs should apply one of 3 buffs.

[Exibit 1](https://www.wowhead.com/spell=16595/noggenfogger-elixir)
[Exibit 2](https://www.wowhead.com/spell=16593/noggenfogger-elixir)
[Exibit 3](https://www.wowhead.com/spell=16591/noggenfogger-elixir)

**Steps to reproduce the problem:**

1. Complete quest chain starting with "The Thirsty Goblin", started at Marin Noggenfogger
2. Recieve, then drink Noggenfogger Elixir
3. Observe

**rev. hash/commit:** 

Sunstrider rev. 10570 (2eecf786f40e) 2019-02-26 18:08:10 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Fixed with 10579
