### ISSUE TITLE
[NPC] Flightmaster Krill Bitterhue (16822)

### ISSUE THREAD

**Issue by BarrensJerk** [ValorenWoW/sunstrider-issues#723]
**Current behaviour:**

NPC is on top of stable roof in Honor Hold

**Expected behaviour:**

NPC should be on the ground next to the gryphon in the nest

**Steps to reproduce the problem:**

1. Go to Honor Hold
2. Try to talk to the flightmaster
3. Realise he is on top of the stable roof.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 
10570

**Comment by kelno** [comment]
He was feared there. That was fixed some days ago, it won't happen again for any of the npcs there.
