### ISSUE TITLE
[Mechanics] Stealth levels seem to not be working correctly

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#727]
**Description:**

A lot of creatures and players can be seen in stealth from very far, doesn't seem to be working correctly.
Can be seen on any creature in an instance or players (especially not level 70 players, those seemed to be working correctly)

This needs more close examination

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/068a550b04df8da53133ecb13294273e9865893a

**Comment by kelno** [comment]
For stealth level: https://github.com/ValorenWoW/sunstrider-issues/issues/633
