### ISSUE TITLE
[Mage] Combustion doesn't stack with critical hits

### ISSUE THREAD

**Issue by BarrensJerk** [ValorenWoW/sunstrider-issues#728]
**Description:**

Combustion should gain stacks with each successful fire spell hit
When activated, this spell causes each of your Fire damage spell hits to increase your critical strike chance with Fire damage spells by 10%. This effect lasts until you have caused 3 critical strikes with Fire spells.

https://wowwiki.fandom.com/wiki/Combustion_(old)

**Current behaviour:**

Combustion not gaining stacks with crits

**Expected behaviour:**

Crits and non crits should add a stack to combustion

**Steps to reproduce the problem:**

CHANGEME
1. Spec combustion
2. Cast combustion
3. Take note of stacking combustion only when non crits land, not all successful spell casts

**rev. hash/commit:** 

rev. 10570

**Comment by Jerrythemagicdog** [comment]
Fixed in 10622
