### ISSUE TITLE
[Professions] Cannot unlearn professions

### ISSUE THREAD

**Issue by BarrensJerk** [ValorenWoW/sunstrider-issues#729]
**Description:**

Cannot unlearn professions once learned from trainer, via the little icon to the right hand side of the profession bar in character / Skills panel

**Current behaviour:**

If using the SuperHelper, professions taught by it can easily be unlearned as they should, via opening the character panel, clicking on Skills, scrolling to Professions, and when highlighting a profession simply click the little crossed circle icon to the right of the profession bar and confirm unlearn.

When trained in game by the actual profession trainer, professions are missing that little unlearn icon

**Expected behaviour:**

Should be able to unlearn professions once picked up by opening character panel, clicking skills, and highlighting the profession and clicking the little unlearn icon. 

**Steps to reproduce the problem:**

CHANGEME
1. Roll a fresh level 1 character, port to start zone
2. Level to 5
3. Visit major city and pick up a couple professions
4. They cannot be unlearned 

![wowscrnshot_030219_165021](https://user-images.githubusercontent.com/44628946/53678478-6500da00-3d0b-11e9-963a-993ecf024f66.jpg)

**rev. hash/commit:** 

rev 10570

**Comment by BarrensJerk** [comment]
Without any addons problem still present

![wowscrnshot_030219_165250](https://user-images.githubusercontent.com/44628946/53678499-b14c1a00-3d0b-11e9-836d-a118dd1c4b47.jpg)

**Comment by BarrensJerk** [comment]
Professions learned via Super Helper have the icon present

![wowscrnshot_030219_165410](https://user-images.githubusercontent.com/44628946/53678519-e7899980-3d0b-11e9-885b-1426359eeabd.jpg)

**Comment by kelno** [comment]
Fixed with 10700
