### ISSUE TITLE
Warlock's backlash proc's are being consumed by hard-cast SB's (similar to other caster's procs)

### ISSUE THREAD

**Issue by Kaziner** [ValorenWoW/sunstrider-issues#746]
**Description:**

Warlock's backlash proc is being consumed when a shadowbolt is hard-cast when it should only be consumed when it actually gives the spell cast reduction

**Current behaviour:**

Warlock's backlash proc is being consumed when a shadowbolt is hard-cast when it should only be consumed when it actually gives the spell cast reduction

**Expected behaviour:**

Warlock's backlash proc is being consumed when a shadowbolt is hard-cast when it should only be consumed when it actually gives the spell cast reduction

**Steps to reproduce the problem:**

CHANGEME
1. Be a warlock
2. Shadowbolt spam on a target 
3. Get hit by a mob while doing it
4. Watch that if you get a backlash proc mid-cast; when you finish your cast it will consume the charge instead of giving your next SB the 0 cast time

rev 10570

https://db.excalibur.ws/?spell=34939
https://db.excalibur.ws/?spell=27209

**Comment by kelno** [comment]
Should be fixed with 10590 already
See https://github.com/ValorenWoW/sunstrider-issues/issues/681
