### ISSUE TITLE
[Priest] Reflective Shield scales with healing or spell damage

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#760]
**Description:**

Priest's talent Reflective Shield (33205 for rank 5) scales with bonus healing or spell damage, resulting in a lot of damage reflected (up to 700 per tick). The damage it does should not scale with BH or SPD, but only reflect a flat % value of what the shield absorbs.

https://wow.gamepedia.com/index.php?title=Reflective_Shield&oldid=1287572

**rev. hash/commit:** 
rev. 10603

**Comment by kelno** [comment]
Fixed with 10617
