### ISSUE TITLE
[Priest] Reflective Shield damage keeps both parties in combat

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#761]
**Description:**

Reflective Shield damage keeps both the player who absorbs and the player who takes damage in combat for the duration of the shield. It should not keep people in combat and should also not interrupt eating. 

**rev. hash/commit:** 

10603

**Comment by kelno** [comment]
Fixed with https://github.com/kelno/sunstrider-core/commit/b1412273557444f2a5b5a232d82f663e670c8f3c
