### ISSUE TITLE
[Mechanics] Resilience doesn't seem to work correctly

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#762]
**Description:**
All of the tests here are anecdotal and based on feeling, so might not be 100% accurate:
1. Resilience doesn't reduce the probability of critcial strikes correctly
2. The critical strike damage doesn't get reduced
3. The amount of mana drained also doesn't get reduced 

The critical strike damage applied by classes (tested on Rogue and Mage) doesn't seem to be reduced by the correct amount, also their critical strike chance appears to be too high. Tests were done on a 474 Resilience character (almost capped), and the damage reduction was far too low for the amount of it.
Needs more testing.

**Sources:** 
https://wow.gamepedia.com/index.php?title=PvP_Resilience&oldid=1313666

**rev. hash/commit:** 

10603

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/063f52e0a23a8e581b247044cd08c304c7ec896f
