### ISSUE TITLE
[Mage] Cold Snap initializes a Global Cooldown.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#764]
**Description:**
Using Cold Snap (11958) doesn't reset the GCD on Frost spells. It only does so visually.

Steps to reproduce: 
use Cone of Cold, cast Cold Snap immediately , we should be able to use cone of Cone of Cold again but we're not, even though visually we are.

**rev. hash/commit:** 

rev. 10603

Source:
https://youtu.be/IB7bUNWTlh4?t=215
https://youtu.be/IB7bUNWTlh4?t=320
and all throughout the video where Cold Snap is not affected by, or doesn't trigger, a GCD.

**Comment by kelno** [comment]
Fixed

**Comment by Kraizn** [comment]
> **Description:**
> Using Cold Snap (11958) doesn't reset the GCD on Frost spells. It only does so visually.
> 
> Steps to reproduce:
> use Cone of Cold, cast Cold Snap immediately , we should be able to use cone of Cone of Cold again but we're not, even though visually we are.
> 
> **rev. hash/commit:**
> 
> rev. 10603
> 
> Source:
> https://youtu.be/IB7bUNWTlh4?t=215
> https://youtu.be/IB7bUNWTlh4?t=320
> and all throughout the video where Cold Snap is not affected by, or doesn't trigger, a GCD.

The Titel of this bug report states : "Cold Snap initializes a Global Cooldown" and description states " Using Cold Snap (11958) doesn't reset the GCD on Frost spells. It only does so visually." These are two complete different things. Cold snap did never initialize a GCD at all. And the GCD reset under the circumstance that it was triggered by one of the spells that get a CD-Reset by Cold Snap is a visual issue. 

This bug report was completly invalid. Where is the proof that **"use Cone of Cold, cast Cold Snap immediately , we should be able to use cone of Cone of Cold again but we're not, even though visually we are."** is even true ?
The 2 sources that was linked in the report doesnt even show using cold snap within a GCD after cone of cold. And yes Cold snap itself is not supposed to trigger a GCD - but it never did that anyways.

Cold snap was working correct before this "fix" which made a visual bug into a functional one.
