### ISSUE TITLE
[Rogue] Arcane Missiles breaks Vanish

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#766]
**Description:**

Using Rogue's Vanish (26889) when a Mage is casting Arcane Missiles doesn't stop him from casting Arcane Missiles (it should, the target disappears) and breaks Rogue's Vanish also continuing to deal damage to him. 
When a Rogue vanishes during an Arcane Missile channel our cast should be interrupted because the target no longer exists.

**Current behaviour:**

Heat-seeking missiles.

**rev. hash/commit:** 
rev. 10603

**Comment by Jerrythemagicdog** [comment]
Fixed

**Comment by hufsa** [comment]
I cannot see in which commit this was fixed so I don't know how it was fixed. I think the behaviour should be similar for Feign Death as well. Do we know if that's working as intended at the moment?

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/3efd666251c5a4c778044b4a4171f4c90a4b0248
