### ISSUE TITLE
[Mage] Arcane Missiles interaction with haste

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#767]
**Description:**
Current interaction of Arcane Missiles with haste is incorrect. What's happening is we only fire a few missiles (if we use a lot of haste effects) and miss out on the others, or if we only have some more haste there is a visual 6th missile fired off that doesn't do damage but fires after the channeling is already finished.

**Current behaviour:**

The overall cast time should be shorter and the missiles fired off closer to each other. There should always only be 5 missiles fired off, the only difference between cast times should be as to what is the interval between them. 

**rev. hash/commit:** 

rev. 10603

**Comment by kelno** [comment]
Fixed with 10624
