### ISSUE TITLE
[General] Panic-spamming a Bandage makes cast time disappear.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-issues#769]
**Description:**

When we spam Bandage on ourselves the casting bar disappears even though the effect continues. 
The cast bar should definitely not disappear. 
For example spam Heavy Netherweave Bandage (21991) on yourself and see that your cast bar disappears.

**rev. hash/commit:** 

rev. 10603

**Comment by kelno** [comment]
Maybe that's how mr woiwoz managed to get the blizzard cast bar disappear as well

**Comment by kelno** [comment]
Fixed with 10611
