### ISSUE TITLE
[Arathi Basin] - Pulsing win every second after BG Ends

### ISSUE THREAD

**Issue by Cheelout** [ValorenWoW/sunstrider-issues#778]
**Description:**

After Arathi Basin ends, it pulses its win and rewards 3 tokens every seconds until you leave the battle ground

**Current behaviour:**

After Arathi Basin ends, it pulses its win and rewards 3 tokens every second until you leave the battle ground

![image](https://user-images.githubusercontent.com/38281939/54467313-5f5dc680-47d8-11e9-9246-04e1a6850769.png)

**Expected behaviour:**

Like each other BG it should only pulse win once, and reward 3 tokens.
Tested WSG / AV / EOTS and none of these have the same issue.

**Steps to reproduce the problem:**

CHANGEME
1. Win Arathi Basin

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

![image](https://user-images.githubusercontent.com/38281939/54467306-55d45e80-47d8-11e9-8e52-494cbd9dcc05.png)

**Comment by kelno** [comment]
Fixed with 10662
