### ISSUE TITLE
[Duels] DoT Effects not disappearing after duel ends

### ISSUE THREAD

**Issue by Arissarlia** [ValorenWoW/sunstrider-issues#789]
**Description:**

Damage over Time effects ticking overtime after duel ends.

**Current behaviour:**

Damage over Time effects stay on the target well after the duel ends and continues ticking down instead of disappearing after the duel ends, causing the player to die.

**Expected behaviour:**

Damage over Time effects should disappear after a duel ends and not continue ticking to kill the person after the duel ends.

Can see the DoT effects disappear in a duel here - https://youtu.be/3I6n0besdRE?t=110

**Steps to reproduce the problem:**

1. Make sure you are a class that has a DoT effect such as a Priest / Warlock
2. Duel someone of the same faction as you.
3. Melt their Face
4. Watch them die in-front of you after the duel ends.
5. Flex

**rev. hash/commit:** 

![serverinfo](https://user-images.githubusercontent.com/48640427/54486207-13447c00-48d5-11e9-8fb1-749becb73aae.jpg)

**Comment by kelno** [comment]
Probably fixed with 10662
