### ISSUE TITLE
Pet Damage

### ISSUE THREAD

**Issue by Azytheoneandonly** [ValorenWoW/sunstrider-issues#795]
**Description:**

Pet Melee damage seems to be way higher than intended.

**Current behaviour:**

Pet Melee damage is doing .. i would say about 1.5 to 2 times the damage it should be doing
Hunter Wind Serpent Damage against 60 mage in Duel without Bestial Wrath activated (Hits not Crit.)
![Screen Shot 03-20-19 at 05 18 AM](https://user-images.githubusercontent.com/37324574/54643366-72c3a700-4ae2-11e9-99ad-d14c055e6e03.JPG)

Naked Warlock attacking mobs in Dun Morogh below with Felguard

![image](https://user-images.githubusercontent.com/37324574/54643335-5889c900-4ae2-11e9-89e8-17e9defd5ee7.png)

**Expected behaviour:**

Pet Damage should be reduced. 

**Steps to reproduce the problem:**

1. Log onto hunter / warlock
2. Send pet in 
3. Watch it wreck stuff

![image](https://user-images.githubusercontent.com/37324574/54643521-de0d7900-4ae2-11e9-8e81-b2dbccca8128.png)

**Comment by kelno** [comment]
Does this happen on a hunter without any talents?
If yes, with which pet? + The character name on which that does happen

**Comment by Azytheoneandonly** [comment]
No Talents still dealing a lot of damage. Wind Serpent. Char name is Azyhunter

![image](https://user-images.githubusercontent.com/37324574/54709000-5bdb8e00-4b90-11e9-8e8c-e47cbc7ef341.png)

**Comment by Azytheoneandonly** [comment]
Another one of my 60 hunters. Sofelle no talents. (just logged in for first time and got a free respec but it still has spirit bond somehow)
![image](https://user-images.githubusercontent.com/37324574/54709667-ac9fb680-4b91-11e9-98f2-0e3a8bd22349.png)

**Comment by Cheelout** [comment]
Pet damage is not being scaled down for newly tamed pets either.

**Comment by kelno** [comment]
Thanks for details

**Comment by kelno** [comment]
Which creature did you tame? I went and tamed some random pets with no talents and did not meet the problem.

**Comment by kelno** [comment]
Okay I went and tamed a "Son of Hakkar" and can reproduce the bug

**Comment by kelno** [comment]
Fixed with 10713 for hunter pets. If something is happening with the Warlock pets, this is yet another issue. Will close this one until then, make a new one with more details about warlock pets if there is a problem with them!
