### ISSUE TITLE
Stealth Broken (New)

### ISSUE THREAD

**Issue by emorelix** [ValorenWoW/sunstrider-issues#798]
**Description:**

Stealth on rogue lvl 60 - can be seen by low level mobs from aggro range.

**Current behaviour:**

lvl 55 ogre in deadwind pass ((Deadwind Ogre Mage)) can see me in stealth from aggro range when in frontal cone

**Expected behaviour:**

Mob should only be able to see me in stealth when i am close to it, not 20 yards away.

**Steps to reproduce the problem:**
Enter stealth.
Enter frontal cone of npc 55 ogre in deadwind pass (Deadwind Ogre Mage)
Get aggro from monster.
Stealth is instantly removed as you enter combat.

**Comment by emorelix** [comment]
mobs in BRD also aggro onto me after successful pickpocket attempts from behind, even if sapped. Unsure if this is a related issue. cannot show logs as there is no resist or anything in combat, even if pickpocket is successful,  i still get taken out of stealth for some reason by the mobs.

**Comment by emorelix** [comment]
New thing i noticed about this bug, you get removed from stealth as soon as the mobs see you and enter combat. Even if you are not hit by the mobs, as soon as they target you, stealth is removed.

**Comment by kelno** [comment]
That's https://github.com/ValorenWoW/sunstrider-issues/issues/471

**Comment by emorelix** [comment]
> That's #471

It is not the same issues unfortunately. It may have the same issues as that post, but this is about the level of stealth, more then stealth breaking from entering combat. I get seen from 30 yards away by mobs 15 levels lower then me

**Comment by kelno** [comment]
Yes I meant for your last message only (else I'd have closed this issue).

**Comment by kelno** [comment]
Reworked a bit log with 10720, should be fine now!
