### ISSUE TITLE
Stealth is broken still

### ISSUE THREAD

**Issue by BrockSamson1** [ValorenWoW/sunstrider-issues#803]
**Description:**

Mobs see through stealth, aggroing at normal aggro distance rather than reduced to allow for invisibility. They also draw attention from large distances to the player character when they enter stealth mode.

**Current behaviour:**
Mobs become aggressive at range, this drops stealth from the character, mobs close distance to engage.

**Expected behaviour:**

Mob should not be able to see through stealth. Additionally if a stealthcheck fails and a mob happens to see through this does not break stealth, stealth is broken only on damage taken not at combat entry.

**Steps to reproduce the problem:**
Attempt to engage mob from stealth

**Comment by Nolin7777** [comment]
duplicate
