### ISSUE TITLE
Elemental Mastery - Shaman

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-issues#820]
**Description:**

Elemental Mastery talent/spell ID # 16166 is not being consumed from all offensive spells.

**Current behaviour:**

Using shock spells such as Earth Shock # 10414 or Frost Shock # 10473 or Flame Shock # 29228
Does not consume the buff on the player of Elemental Mastery # 16166
Those spells still crit and cost no mana though.

**Expected behaviour:**

Any offensive spell should consume the Elemental Mastery buff

**Steps to reproduce the problem:**

1. Player casts Elemental Mastery
2. Player uses Earth Shock, it crits and costs no mana
3. Player still has Elemental Mastery buff, can continue to use shock spells with benefits.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

To be added  -server offline

**Comment by kelno** [comment]
Fixed with 10713

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/c5f6127c4072b4e8ce99dccd7e3e3fb6e5a35117
