### ISSUE TITLE
Weapon Skills not training

### ISSUE THREAD

**Issue by Calebizza** [ValorenWoW/sunstrider-issues#823]
**Description:**

Weapon skills not training properly or at all

**Current behaviour:**

when attacking mob with a weapon with a low weapon skill level that weapon skill does not level up

**Expected behaviour:**

weapon skills should gain xp depending on the mob level/defence rating

**Steps to reproduce the problem:**

1. equip new weapon with a lower weapon skill than necessary (I DID NOT TRAIN A NEW WEAPON SKILL)
2. attack mob
3. don't gain weapon skill xp

**rev. hash/commit:** 

Sunstrider rev. 10713 (c5f6127c4072) 2019-03-21 17:29:11 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Closing this one and keeping https://github.com/ValorenWoW/sunstrider-issues/issues/826
