### ISSUE TITLE
Weapon skill slowly leveling

### ISSUE THREAD

**Issue by qoth** [ValorenWoW/sunstrider-issues#826]
**Description:**

Weapon skill slow leveling. May be related to issue https://github.com/ValorenWoW/sunstrider-issues/issues/823

**Current behaviour:**

Weapon skill at level 60 vs another close level mob (tested 55, 56 and 58) is gaining levels at a very slow rate. Talking about 50 + swings without a level, sometimes plateauing.

**Expected behaviour:**

Not sure on the exact rate but it should be much faster.

**Steps to reproduce the problem:**

1. Take a toon that does not have max weapon skill and equip relative weapon.
2. Find a mob with similar level to you.
3. Begin auto attack and watch as levels slowly trickle in.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/54799621-ed8ced80-4cad-11e9-9333-0b973dd42b05.png)

**Comment by kelno** [comment]
Fixed with 10717
